Repository openscilab/nava, pull requests merged in 2023-06, with the labels that each got.

#8 Document
  CHANGELOG.md
  README.md
  nava/__init__.py
  others/meta.yaml
  setup.py
Labels: documentation

#9 Version 0.1
  CHANGELOG.md
  README.md
  others/donation.png
Labels: release

#14 Add release instructions
  others/RELEASE.md
Labels: documentation

#15 `args` tuple assignment issue
  CHANGELOG.md
  nava/functions.py
Labels: bug

#21 remove extra positional argument
  CHANGELOG.md
  nava/functions.py
Labels: bug

#22 Fix for decorator hides parameters
  nava/functions.py
Labels: bug
