Repository openscilab/nava, pull requests merged in 2023-07, with the labels that each got.

#23 Test
  .coveragerc
  .github/workflows/linux_test.yml
  .github/workflows/macOS_test.yml
  .github/workflows/windows_test.yml
  CHANGELOG.md
  README.md
  codecov.yml
  nava/functions.py
  others/test.wav
  pytest.ini
  test/error_test.py
  test/function_test.py
Labels: test

#24 Conda package
  .github/workflows/publish_conda.yaml
  CHANGELOG.md
  README.md
  codecov.yml
Labels: package

#25 Version 0.2
  CHANGELOG.md
  README.md
  nava/params.py
  others/meta.yaml
  others/version_check.py
  setup.py
Labels: release

#28 Async feature implementation using threading library
  .gitignore
  AUTHORS.md
  nava/__init__.py
  nava/functions.py
Labels: enhancement, new feature
