Repository openscilab/nava, pull requests merged in 2024-01, with the labels that each got.

#29 Async mode fix
  .github/workflows/windows_test.yml
  CHANGELOG.md
  README.md
  autopep8.bat
  autopep8.sh
  nava/__init__.py
  nava/functions.py
  nava/params.py
  nava/thread.py
  test/error_test.py
  test/function_test.py
Labels: enhancement, refactoring, major

#30 Python 3.12
  .github/workflows/linux_test.yml
  .github/workflows/macOS_test.yml
  .github/workflows/windows_test.yml
  CHANGELOG.md
  pytest.ini
  setup.py
Labels: test, minor

#32 Badges
  CHANGELOG.md
  README.md
Labels: documentation, minor

#33 Version 0.3
  CHANGELOG.md
  README.md
  nava/params.py
  others/meta.yaml
  others/version_check.py
  setup.py
Labels: release
