Repository openscilab/nava, pull requests merged in 2024-02, with the labels that each got.

#35 Orphan processes
  CHANGELOG.md
  nava/thread.py
  test/function_test.py
Labels: bug

#36 Modern template for Issues/Bug
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CHANGELOG.md
  others/RELEASE.md
  others/version_check.py
Labels: documentation, enhancement, minor

#37 Tests
  CHANGELOG.md
  others/manual_test.py
  others/test.wav
  test/function_test.py
Labels: test

#38 Minor edits
  .github/dependabot.yml
  CHANGELOG.md
  README.md
  others/RELEASE.md
Labels: documentation

#39 Version 0.4
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  nava/params.py
  others/meta.yaml
  others/version_check.py
  setup.py
Labels: release
