Repository openscilab/nava, pull requests merged in 2024-04, with the labels that each got.

#42 Version 0.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  nava/params.py
  others/meta.yaml
  others/version_check.py
  setup.py
Labels: release

#43 Manual test checklist
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: documentation, enhancement

#44 SECURITY.md
  .github/CODE_OF_CONDUCT.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  SECURITY.md
  others/RELEASE.md
  others/version_check.py
  setup.py
Labels: documentation
